import os


CURRENT_WORKING_DIR = os.path.abspath(os.getcwd())
CLOUD_CONFIG_NAME = "{}_config.json"
CLOUD_CONFIG_DIR = os.path.join(CURRENT_WORKING_DIR, 'src')
CLOUD_CONFIG_PATH = os.path.join(CLOUD_CONFIG_DIR, CLOUD_CONFIG_NAME)
CONFIG_OUTPUT_FILE_NAME = 'config.json'
CONFIG_OUTPUT_FILE_DIR = os.path.join(CURRENT_WORKING_DIR, 'src')
CONFIG_OUTPUT_FILE_PATH = os.path.join(CONFIG_OUTPUT_FILE_DIR, CONFIG_OUTPUT_FILE_NAME)